# =====================================
# EMAIL SENDER MODULE
# =====================================
import smtplib
from email.mime.text import MIMEText
from email.mime.multipart import MIMEMultipart
import os
from dotenv import load_dotenv
import logging
import pandas as pd
from typing import List, Dict

load_dotenv()

logging.basicConfig(level=logging.INFO)
logger = logging.getLogger(__name__)


def format_doctors_html(doctors_list: List[Dict]) -> str:
    """Format doctors list into HTML table"""
    if not doctors_list:
        return "<p>No specialist doctors found at this time.</p>"
    
    html = """
    <table style="width: 100%; border-collapse: collapse; margin: 20px 0;">
        <thead>
            <tr style="background: #f3f4f6;">
                <th style="padding: 12px; text-align: left; border-bottom: 2px solid #e5e7eb; font-weight: 600;">Doctor Name</th>
                <th style="padding: 12px; text-align: left; border-bottom: 2px solid #e5e7eb; font-weight: 600;">Specialization</th>
                <th style="padding: 12px; text-align: left; border-bottom: 2px solid #e5e7eb; font-weight: 600;">Experience</th>
                <th style="padding: 12px; text-align: left; border-bottom: 2px solid #e5e7eb; font-weight: 600;">Hospital</th>
                <th style="padding: 12px; text-align: left; border-bottom: 2px solid #e5e7eb; font-weight: 600;">Phone</th>
            </tr>
        </thead>
        <tbody>
    """
    
    for doc in doctors_list:
        html += f"""
            <tr>
                <td style="padding: 12px; border-bottom: 1px solid #e5e7eb;">{doc['doctor_name']}</td>
                <td style="padding: 12px; border-bottom: 1px solid #e5e7eb;">{doc['specialization']}</td>
                <td style="padding: 12px; border-bottom: 1px solid #e5e7eb;">{doc['experience']} years</td>
                <td style="padding: 12px; border-bottom: 1px solid #e5e7eb;">{doc['hospital_branch']}</td>
                <td style="padding: 12px; border-bottom: 1px solid #e5e7eb;">{doc['phone_number']}</td>
            </tr>
        """
    
    html += """
        </tbody>
    </table>
    """
    return html


def format_input_data_html(input_data: list, field_names: list) -> str:
    """Format input data into HTML table"""
    html = """
    <table style="width: 100%; border-collapse: collapse; margin: 20px 0;">
        <thead>
            <tr style="background: #f3f4f6;">
                <th style="padding: 12px; text-align: left; border-bottom: 2px solid #e5e7eb; font-weight: 600;">Parameter</th>
                <th style="padding: 12px; text-align: left; border-bottom: 2px solid #e5e7eb; font-weight: 600;">Value</th>
            </tr>
        </thead>
        <tbody>
    """
    
    for field, value in zip(field_names, input_data):
        html += f"""
            <tr>
                <td style="padding: 12px; border-bottom: 1px solid #e5e7eb;">{field}</td>
                <td style="padding: 12px; border-bottom: 1px solid #e5e7eb;">{value}</td>
            </tr>
        """
    
    html += """
        </tbody>
    </table>
    """
    return html


def create_html_email(
    disease_name: str,
    result: int,
    doctors_list: List[Dict],
    input_data: list = None,
    field_names: list = None,
    timestamp: str = None
) -> str:
    """Create beautiful, premium HTML email content"""
    from datetime import datetime
    if not timestamp:
        timestamp = datetime.now().strftime("%B %d, %Y at %I:%M %p")
    
    result_text = "INDICATORS DETECTED" if result == 1 else "NO INDICATORS DETECTED"
    # Colors
    primary_color = "#3B82F6" if disease_name == "Diabetes" else \
                   "#EF4444" if "Heart" in disease_name else \
                   "#F59E0B" if "Liver" in disease_name else "#A855F7"
    
    status_bg = "#FEE2E2" if result == 1 else "#D1FAE5"
    status_text = "#DC2626" if result == 1 else "#059669"
    
    if result == 1:
        message = f"""
            Our AI analysis has identified potential indicators associated with <strong>{disease_name}</strong>. 
            <br><br>
            <div style="background: #FFFBEB; border-left: 4px solid #F59E0B; padding: 16px; margin: 20px 0; color: #92400E; font-size: 14px;">
                <strong>IMPORTANT:</strong> This is a preliminary screening report generated by an AI model. It is not a clinical diagnosis. Please consult one of the recommended specialists below or your primary care physician immediately for a professional evaluation.
            </div>
        """
    else:
        message = f"""
            Our AI analysis did not detect significant indicators for <strong>{disease_name}</strong> in the provided screening data. 
            <br><br>
            Maintaining a healthy lifestyle, regular check-ups, and monitoring any physical symptoms remain essential for long-term wellness.
        """
    
    doctors_section = ""
    if result == 1 and doctors_list:
        doctors_section = f"""
            <h3 style="color: #111827; margin-top: 40px; font-size: 18px; border-bottom: 2px solid #E5E7EB; padding-bottom: 10px;">🩺 Recommended Specialists</h3>
            {format_doctors_html(doctors_list)}
        """
    
    input_data_section = ""
    if input_data and field_names:
        input_data_section = f"""
            <h3 style="color: #111827; margin-top: 40px; font-size: 18px; border-bottom: 2px solid #E5E7EB; padding-bottom: 10px;">📊 Screened Parameters</h3>
            {format_input_data_html(input_data, field_names)}
        """
    
    html_content = f"""
    <!DOCTYPE html>
    <html>
    <head>
        <meta charset="utf-8">
        <style>
            body {{ font-family: 'Segoe UI', Arial, sans-serif; line-height: 1.6; color: #374151; margin: 0; padding: 0; background-color: #F3F4F6; }}
            .container {{ max-width: 600px; margin: 40px auto; background: #FFFFFF; border-radius: 16px; overflow: hidden; box-shadow: 0 10px 25px rgba(0,0,0,0.05); }}
            .header {{ background: linear-gradient(135deg, {primary_color}, #1E3A8A); color: white; padding: 32px; text-align: center; }}
            .content {{ padding: 32px; }}
            .status-badge {{ display: inline-block; padding: 8px 16px; border-radius: 9999px; font-weight: 700; font-size: 14px; background: {status_bg}; color: {status_text}; margin-top: 12px; }}
            .footer {{ background: #F9FAFB; padding: 24px; text-align: center; font-size: 12px; color: #6B7280; border-top: 1px solid #E5E7EB; }}
        </style>
    </head>
    <body>
        <div class="container">
            <div class="header">
                <h1 style="margin: 0; font-size: 24px;">Medical Screening Report</h1>
                <div class="status-badge">{result_text}</div>
            </div>
            <div class="content">
                <div style="display: flex; justify-content: space-between; margin-bottom: 24px; font-size: 14px; color: #6B7280;">
                    <span><strong>Disease:</strong> {disease_name}</span>
                    <span style="text-align: right;"><strong>Date:</strong> {timestamp}</span>
                </div>
                <div style="font-size: 16px;">{message}</div>
                {doctors_section}
                {input_data_section}
            </div>
            <div class="footer">
                <p>© 2026 Medical AI Diagnostics. All rights reserved.</p>
                <p>This email was sent to you as part of your health screening request. If you did not perform this screening, please disregard this message.</p>
            </div>
        </div>
    </body>
    </html>
    """
    return html_content


def send_prediction_email(
    to_email: str,
    disease_name: str,
    result: int,
    doctors_list: List[Dict] = None,
    input_data: list = None,
    field_names: list = None
):
    """Send prediction result email"""

    if not to_email:
        logger.warning("No email address provided")
        return False

    try:
        email_host = os.getenv("EMAIL_HOST", "smtp.gmail.com")
        email_port = int(os.getenv("EMAIL_PORT", "587"))  # ✅ FIXED
        email_user = os.getenv("EMAIL_USER")
        email_pass = os.getenv("EMAIL_PASS")

        if not all([email_host, email_user, email_pass]):
            logger.error("Email configuration missing")
            return False

        message = MIMEMultipart("alternative")
        message["Subject"] = f"{disease_name} Prediction Results - Medical Screening Report"
        message["From"] = email_user
        message["To"] = to_email

        html_content = create_html_email(
            disease_name=disease_name,
            result=result,
            doctors_list=doctors_list or [],
            input_data=input_data,
            field_names=field_names
        )

        html_part = MIMEText(html_content, "html")
        message.attach(html_part)

        # ✅ FIXED SMTP LOGIC (ONLY CHANGE)
        with smtplib.SMTP(email_host, email_port, timeout=20) as server:
            server.ehlo()
            server.starttls()
            server.ehlo()
            server.login(email_user, email_pass)
            server.send_message(message)

        logger.info(f"Email sent successfully to {to_email}")
        return True

    except Exception as e:
        logger.error(f"Failed to send email to {to_email}: {str(e)}")
        return False


def send_appointment_status_email(
    to_email: str,
    doctor_name: str,
    specialization: str,
    hospital_branch: str,
    disease: str,
    status: str,
    date: str = "TBD",
    time: str = "TBD"
):
    """Send appointment status notification (Accepted/Rejected)"""
    if not to_email:
        return False

    try:
        email_host = os.getenv("EMAIL_HOST", "smtp.gmail.com")
        email_port = int(os.getenv("EMAIL_PORT", "587"))
        email_user = os.getenv("EMAIL_USER")
        email_pass = os.getenv("EMAIL_PASS")

        message = MIMEMultipart("alternative")
        status_upper = status.upper()
        message["Subject"] = f"APPOINTMENT {status_upper} - Dr. {doctor_name}"
        message["From"] = email_user
        message["To"] = to_email

        accent_color = "#059669" if status.lower() == "accepted" else "#DC2626"
        
        html_content = f"""
        <!DOCTYPE html>
        <html>
        <head>
            <style>
                body {{ font-family: 'Segoe UI', Arial, sans-serif; line-height: 1.6; color: #374151; }}
                .card {{ max-width: 500px; margin: 20px auto; border: 1px solid #E5E7EB; border-radius: 12px; overflow: hidden; box-shadow: 0 4px 6px -1px rgba(0, 0, 0, 0.1); }}
                .status-header {{ background: {accent_color}; color: white; padding: 20px; text-align: center; }}
                .details {{ padding: 30px; }}
                .footer {{ background: #F9FAFB; padding: 15px; text-align: center; font-size: 11px; color: #9CA3AF; }}
            </style>
        </head>
        <body>
            <div class="card">
                <div class="status-header">
                    <h2 style="margin: 0;">Appointment {status.title()}</h2>
                </div>
                <div class="details">
                    <p>Dear Patient,</p>
                    <p>Your appointment request for <strong>{disease} consultation</strong> has been <strong>{status.lower()}</strong> by the medical specialist.</p>
                    
                    <div style="background: #F3F4F6; padding: 20px; border-radius: 8px; margin: 20px 0;">
                        <p style="margin: 0 0 10px 0;"><strong>Consultant:</strong> {doctor_name}</p>
                        <p style="margin: 0 0 10px 0;"><strong>Specialization:</strong> {specialization}</p>
                        <p style="margin: 0 0 10px 0;"><strong>Location:</strong> {hospital_branch}</p>
                        <p style="margin: 0 0 10px 0;"><strong>Date:</strong> {date}</p>
                        <p style="margin: 0;"><strong>Time:</strong> {time}</p>
                    </div>

                    <p style="font-size: 14px; color: #6B7280;">Please arrive 15 minutes before your scheduled time. Remember to bring your digital screening report and this confirmation letter.</p>
                </div>
                <div class="footer">
                    Sent via Vitalix Quantum Logistics • Confidential Medical Correspondence
                </div>
            </div>
        </body>
        </html>
        """

        message.attach(MIMEText(html_content, "html"))

        with smtplib.SMTP(email_host, email_port, timeout=20) as server:
            server.starttls()
            server.login(email_user, email_pass)
            server.send_message(message)

        logger.info(f"Status email sent to {to_email}")
        return True

    except Exception as e:
        logger.error(f"Failed to send status email: {str(e)}")
        return False

def send_medicine_dispatch_email(
    to_email: str,
    order_id: str,
    total: float
):
    if not to_email:
        return False
    import os, smtplib, logging
    from email.mime.multipart import MIMEMultipart
    from email.mime.text import MIMEText
    try:
        email_host = os.getenv("EMAIL_HOST", "smtp.gmail.com")
        email_port = int(os.getenv("EMAIL_PORT", "587"))
        email_user = os.getenv("EMAIL_USER")
        email_pass = os.getenv("EMAIL_PASS")

        message = MIMEMultipart("alternative")
        message["Subject"] = f"PHARMACY LOGISTICS DISPATCHED - Order {order_id}"
        message["From"] = email_user
        message["To"] = to_email

        html_content = f"""
        <!DOCTYPE html>
        <html>
        <head>
            <style>
                body {{ font-family: 'Segoe UI', Arial, sans-serif; line-height: 1.6; color: #374151; }}
                .card {{ max-width: 500px; margin: 20px auto; border: 1px solid #10B981; border-radius: 12px; overflow: hidden; box-shadow: 0 4px 6px -1px rgba(0, 0, 0, 0.1); }}
                .status-header {{ background: #10B981; color: white; padding: 20px; text-align: center; }}
                .details {{ padding: 30px; }}
            </style>
        </head>
        <body>
            <div class="card">
                <div class="status-header">
                    <h2 style="margin: 0;">Pharmaceuticals Dispatched</h2>
                </div>
                <div class="details">
                    <p>Dear Patient,</p>
                    <p>Your medicine order <strong>#{order_id}</strong> has been officially approved by the Medical Admin and has left the facility.</p>
                    <div style="background: #F3F4F6; padding: 20px; border-radius: 8px; margin: 20px 0;">
                        <p style="margin: 0 0 10px 0;"><strong>Receipt Total:</strong> ₹{total}</p>
                    </div>
                    <p style="font-size: 14px; color: #6B7280;">Expect physical delivery within standard operating protocols.</p>
                </div>
            </div>
        </body>
        </html>
        """
        message.attach(MIMEText(html_content, "html"))

        with smtplib.SMTP(email_host, email_port, timeout=20) as server:
            server.ehlo()
            server.starttls()
            server.ehlo()
            server.login(email_user, email_pass)
            server.send_message(message)
        return True
    except Exception as e:
        return False
